### ISSUE TITLE
Problems with pwnaflipper

### ISSUE THREAD

**Issue by Davim09** [roodriiigooo/PWNAGOTCHI-CUSTOM-FACES-MOD#1]
So I'm having problems with pwnaflipper, after having done the entire process of backing up the files and modifications, it doesn't start the web part, it starts but is frozen, how to solve it??

**Comment by roodriiigooo** [comment]
Hi Davim09

Probably it's some syntax or indentation error.
Try running this command:
```
root@pwnagotchi:/# systemctl stop pwnagotchi
root@pwnagotchi:/# systemctl start pwnagotchi

```
And see if the console returns any useful message, you can also run the pwnagotchi service directly to access these messages in real-time

**Comment by Davim09** [comment]
It worked! I hadn't tested the start command, just the Restart command, thank you very much
